angular.module('myApp', ['ui.router','ui.bootstrap'])
	.config(MyAppConfig)
	.controller('LoginController', LoginController)
	.controller('UserManagementController', UserManagementController)
	.controller('PersonalSettingsController', PersonalSettingsController)
	.controller('RegistrateController', RegistrateController)
	.controller('NotificationController', NotificationController)
	.controller('ResetPasswordModalinstanceController', ResetPasswordModalinstanceController)
	.controller('AdminModalinstanceController', AdminModalinstanceController)
	.factory('LoginService', LoginService)
	.factory('UserManagementService', UserManagementService)
	.factory('PersonalSettingsService', PersonalSettingsService)
	.factory('RegistrateService', RegistrateService)
	.factory('NotificationService', NotificationService)
	.directive('loading', loading);
