angular.module('myApp', ['ui.router','ui.bootstrap'])
	.config(MyAppConfig)
	.controller('LoginController', LoginController)
	.controller('CustomerManagementController', CustomerManagementController)
	.controller('AdminController', AdminController)
	.controller('CustomerController', CustomerController)
	.controller('RegistrateController', RegistrateController)
	.controller('NotificationController', NotificationController)
	.controller('ResetPasswordModalinstanceController', ResetPasswordModalinstanceController)
	.controller('AdminModalinstanceController', AdminModalinstanceController)
	.factory('LoginService', LoginService)
	.factory('CustomerManagementService', CustomerManagementService)
	.factory('AdminService', AdminService)
	.factory('CustomerService', CustomerService)
	.factory('RegistrateService', RegistrateService)
	.factory('NotificationService', NotificationService)
	.directive('loading', loading);
